# Use root/example as user/password credentials
version: '3.1'

networks:
  task-management-net:

volumes:
  db_data:

services:
  db:
    image: mysql
    restart: always
    ports:
      - "3306:3306"
    networks:
      - task-management-net
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: taskRoot2024
      MYSQL_DATABASE: task_management
      MYSQL_USER: task_app
      MYSQL_PASSWORD: tasks2024